# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: local-storage
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer

# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dag-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"
  resources:
    requests:
      storage: 5Gi
  volumeName: airflow-dags
