apiVersion: v1
kind: PersistentVolume
metadata:
  name: dag-pvc
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs-service.airflow.svc.cluster.local
    path: /persistentvolumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dag-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
